#!/usr/bin/env python3
"""Build the keyboard word list (TSV) from a raw Standard Spoken Tamil text file.

Usage:
    python3 build_dictionary.py corpus.txt
    python3 build_dictionary.py corpus.txt more.txt --min-count 2
    python3 build_dictionary.py corpus.txt --prod=true    # update app/src/main/assets/dictionary.tsv

Every run of letters in the input is a candidate word. A candidate is kept only if,
after Unicode NFC normalisation (and lowercasing unless --keep-case), every character
can be typed on the tam_sst keyboard. Tamil-script words, emoji, digits, punctuation
and other symbols are therefore dropped. Frequencies are counted over all input files.
Words are written in the order they first appear; the keyboard ranks them by frequency.

The output follows the format read by DictionaryParser: `word<TAB>frequency`.
"""

import argparse
import re
import sys
import unicodedata
from collections import Counter
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = SCRIPT_DIR.parent / "sample-dictionary.tsv"
PROD_OUTPUT = SCRIPT_DIR.parent / "app" / "src" / "main" / "assets" / "dictionary.tsv"

# Every character on the letter keys of TamSstLayout.kt (all four levels).
KEYBOARD_LETTERS = frozenset(
    "abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "\u01F9\u0146"  # ǹ ņ
    "\u00F9\u00E8"  # ù è
    "\u00E9"        # é
    "\u0157"        # ŗ
    "\u0163"        # ţ
    "\u00EC"        # ì
    "\u00FA"        # ú
    "\u00ED"        # í
    "\u00F3"        # ó
    "\u00E1"        # á
    "\u015F\u015B"  # ş ś
    "\u1E11"        # ḑ
    "\u011F"        # ğ
    "\u00F1"        # ñ
    "\u013C"        # ļ
    "\u01EF"        # ǯ
    "\u00E0\u00E6"  # à æ
    "\u0109"        # ĉ
    "\u0148"        # ň
    "\u014B"        # ŋ
)

# A run of letters and combining marks in any script; everything else separates words.
WORD_RUN = re.compile(r"[^\W\d_]+(?:[\u0300-\u036F\u0B80-\u0BFF][^\W\d_]*)*")

# URLs, e-mail addresses and @mentions are removed before words are extracted.
NOISE = re.compile(r"(?:https?://|www\.)\S+|\S+@\S+|@\w+", re.IGNORECASE)

HEADER = """\
# Standard Spoken Tamil word list used for keyboard suggestions.
# Generated by dictionary-builder/build_dictionary.py from: {sources}
#
# word<TAB>frequency  (higher frequency ranks first)
#
# {count} words, {total} word occurrences counted.
"""


def extract_words(line: str, keep_case: bool):
    line = NOISE.sub(" ", unicodedata.normalize("NFC", line))
    for match in WORD_RUN.finditer(line):
        word = match.group()
        if not keep_case:
            word = word.lower()
        if all(ch in KEYBOARD_LETTERS for ch in word):
            yield word


def count_words(paths, keep_case: bool, min_length: int) -> Counter:
    counts = Counter()
    for path in paths:
        with open(path, encoding="utf-8-sig", errors="replace") as f:
            for line in f:
                counts.update(w for w in extract_words(line, keep_case) if len(w) >= min_length)
    return merge_case_variants(counts) if keep_case else counts


def merge_case_variants(counts: Counter) -> Counter:
    """Collapse spellings that differ only in case into the most frequent one, summing counts."""
    groups = {}
    for word, count in counts.items():
        groups.setdefault(word.lower(), Counter())[word] += count
    merged = Counter()
    for variants in groups.values():
        merged[variants.most_common(1)[0][0]] = sum(variants.values())
    return merged


def parse_bool(value: str) -> bool:
    lowered = value.lower()
    if lowered in ("true", "yes", "1"):
        return True
    if lowered in ("false", "no", "0"):
        return False
    raise argparse.ArgumentTypeError(f"expected true or false, got '{value}'")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("inputs", nargs="+", type=Path, help="UTF-8 text file(s) to read")
    parser.add_argument("--prod", type=parse_bool, nargs="?", const=True, default=False,
                        help=f"true: write the app's word list {PROD_OUTPUT} instead of {DEFAULT_OUTPUT}")
    parser.add_argument("-o", "--output", type=Path,
                        help="TSV file to write (overrides --prod)")
    parser.add_argument("--min-count", type=int, default=1,
                        help="drop words seen fewer times than this (default: 1)")
    parser.add_argument("--min-length", type=int, default=2,
                        help="drop words shorter than this many characters (default: 2)")
    parser.add_argument("--keep-case", action="store_true",
                        help="keep capital letters instead of lowercasing; case variants of a word are "
                             "merged into its most frequent spelling")
    args = parser.parse_args()
    if args.output is None:
        args.output = PROD_OUTPUT if args.prod else DEFAULT_OUTPUT

    for path in args.inputs:
        if not path.is_file():
            parser.error(f"input file not found: {path}")

    counts = count_words(args.inputs, args.keep_case, args.min_length)
    entries = [(w, c) for w, c in counts.items() if c >= args.min_count]

    seen = set()
    for word, _ in entries:
        key = unicodedata.normalize("NFC", word).lower()
        if key in seen:
            sys.exit(f"error: duplicate word '{word}'; output not written")
        seen.add(key)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(
            sources=", ".join(p.name for p in args.inputs),
            count=len(entries),
            total=sum(c for _, c in entries),
        ))
        for word, count in entries:
            out.write(f"{word}\t{count}\n")

    print(f"Wrote {len(entries)} words to {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
